spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

token:
  secret: ${jwt-token-secret} # todo 자신의 jwt token secret키 입력
  access-token-expiration-time: 900000  # 15분
  refresh-token-expiration-time: 1210500000 # 2주\
