spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/shop
    username: ${database-user}
    password: ${database-password}

  jpa:
    hibernate:
      ddl-auto: none
